env:
  - secure: "bS72zP1LR58n/wiJ98AhWzmwieATdhDYmQUFQ0DSwasy+IhK5hbL9FFKlLMqXnVOpT1z9td2JLao6oyRLZ8ULlu8jDl8gVO44xSepoGmerk1iI/teX4RBjH9ixQojdJRxjvqD3XbJed+ZR2BxewoLMTQf3QPf5zMtaM/Ml5NfdFVI2f2iKQWTtC0i/9vvOqXAKtl6l055nXKmKow20XPcAZFFLzPwU1jlcq7gTW9GdjosVhI7WkfysICkh0odmtN/i1/o/lNNl+HC1xBL0DHOkiC/NogA+EKr2uxwmkAG3bHuXxCIHqD06fIyKPE+ugzDMJGlbi+A5JS1BZQvcbcCU2fCdp+uILevCocrcDUwCUvxN28LRdDyzQzaIR94RmV5xeZW6iJUh7bbXVe636TveIwUHOPAofIj22/XIonXsBLV5J+muk1GSPjhKHsgEetgQGcUS+rCXjf4HTXv5XOA7eAS20lyhvmbLFikSm3Qj/6V/UXq3+5krqQ9IcGRWjBo5V55/L6MSVp93H1v8+cjosIcPMj7Ubfa065kiZ81UWvdI8/piN45uNPUQC345CZfb9VhsjfUhGcNm8tyUY6OkGmkgfwg6iI0DcfOZzK5NDw+OF9Jj7Ke+T1raCxpddElVKf9b4MGiXMsARLtl8yciINiHmmliaahmusSRMgi8g="
  - secure: "Xj6XVDkfwupYp/5H/IUG5l/vZGnulZACPmMwal7/7273+l6ohER1+aSpehJ/sApGtDUBZkZ8fLVh26vPsHYR6RRi2NSSWev5olZ4EBFx/VhlXsrt65UL/W+PnvZTjwdSgyn4TTuT5hx48qChPDhnf0sKHsQT5QC0Df6YYv0oQw1QpsB1kXN5gSHI05bAHTiawacTPEVf3xvVSNNeRZvBHXMQeVxxcIEFqJiW2MBIdjdOuOzyasMuNWOvJ6f9thK9bZfs/tH2GHy3jIjLxxLrOMBTMfyK+G9oVpWeMBDLa0fnPMYEo8i5n/UVDD6xhNvCZoipPwzcx3Ool59Vr4wj/aDHUyYuY+W16AFmXcsCkPi3F1Vg2Lya+GSHXxRCbP0o/GXXC3e0laJKW1c9ICBsY1b2ZUDrsL375EsgFBx+F+SR1WYqpavoMmVpbSEcqktY/gJVz379z7zLhqyhyK9I8xOoYHDP4OO51J+gFxVJ0gNt7QZjX84Yf35JwrtVbpAa8qMdqePZOrT05/weHIX2mwUhhtlVkF2fIggm1tQVUnBTbJkr+yJH1c3NwpNhu/lBbFZUKx4W0CoIK3G+Tcnv5DlOF0DloD9+TwGDmbahZ9DMK0KdMC1HCKgAcrXqa7pO/V18p+u+wy5nL64J23wMW5QGSZ1sPDfUIpNa0CVGbWM="

language: scala

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - pip install --user codecov
after_success:
  - codecov
